language: haskell

env:
  matrix:
    - GHCVER=7.10.3 CABALVER=1.22 SKIP_HADDOCK=true
    - GHCVER=8.0.2 CABALVER=1.24
    - GHCVER=8.2.2 CABALVER=2.0
    - GHCVER=8.4.3 CABALVER=2.2
    - GHCVER=8.6.5 CABALVER=2.4
    - GHCVER=8.8.1 CABALVER=3.0
    - GHCVER=head CABALVER=head
  global:
      - HEAD_DEPS="diagrams-core diagrams-lib diagrams-solve monoid-extras dual-tree"

matrix:
    allow_failures:
    - env: GHCVER=head CABALVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313SVGFonts\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
